version: '3.9'
services:
    mysqldb:
        image: mysql:latest
        container_name: loja-db
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: 'loja'
            MYSQL_ROOT_PASSWORD: root123
            MYSQL_TCP_PORT: 3306
        ports:
            - 3307:3306
        expose:
            - 3306
        healthcheck:
            test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
            timeout: 30s
            retries: 10
        networks:
            - mynet
    app:
        depends_on:
            - mysqldb
        build:
            dockerfile: Dockerfile
            context: .
        links:
            - mysqldb:database
        environment:
            MYSQL_HOST: mysqldb
            MYSQL_LOCAL_PORT: 3306
            MYSQL_DATABASE: 'loja'
            MYSQL_USERNAME: 'root'
            MYSQL_PASSWORD: 'root123'
            MYSQL_ROOT_PASSWORD: 'root123'
        networks:
            - mynet
        container_name: lojinha
        restart: unless-stopped
        ports:
            - 3000:3000
        expose:
            - 3000
        volumes:
            - C:\Users\thomaz.josetti\Desktop\mysql:/var/lib/mysql
networks:
    mynet:
        external : true
        name:  mynet
        driver: bridge
