export const TYPEORM_TOKENS = {
    USER_REPOSITORY: Symbol.for('USER_REPOSITORY'),
    ROLES_REPOSIOTRY: Symbol.for('ROLES_REPOSIOTRY'),
    USER_PERMISSION_REPOSIOTRY: Symbol.for('USER_PERMISSION_REPOSIOTRY')
} as const;
